# Site settings
title: "Giovanni Ballarin"
description: "Online resume for Giovanni Ballarin"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Giovanni Ballarin"
resume_title:                   "📓 Student of Economics"
resume_contact_email:           "gn.ballarin@icloud.com"
resume_contact_telephone:       ""
resume_contact_address:         ""
resume_header_contact_info:     "Cremona - Rome - Konstanz"
resume_header_intro:            ""

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
blog:                           "yes"
blog_link:                      "https://giob1994.github.io/blog/"
resume_looking_for_work:        "yes"
resume_downloadable:            "yes"
resume_filename:                "cv_giovanni_ballarin.pdf"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
    resume_github_url:            "https://github.com/giob1994"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
    resume_facebook_url:          "https://www.facebook.com/people/Giovanni-Ballarin/100001433324871"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
