#
#

title: Giovanni Ballarin
url: 
baseurl: 

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Giovanni Ballarin - 2019"
footer_url: "https://github.com/ankitsultana"
footer_credit: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "/resume"
 - name: "Contact"
   link: "/contact"
   
# ===========================

exclude: [old]
